### ISSUE TITLE
ban for an mastake in the system

### ISSUE THREAD

**Issue by TheRaveninGitHub** [notsamicc/Fortnite-Builds#10]
hi, i have been banned from the rift fortnite discord server, 1 i dont have 60bux to spend on an vpn 2, i have been ip banned so no alt accounts

please HELP and not be idiots

**Comment by notsamicc** [comment]
what's your discord and why did you get banned

**Comment by TheRaveninGitHub** [comment]
I got banned for"Bad words" but in reality I posted a log file

**Comment by TheRaveninGitHub** [comment]
my discord is Ship 20 With Booster 4#2040

**Comment by notsamicc** [comment]
i've unbanned you
