### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by CoolNiteYT** [notsamicc/Fortnite-Builds#14]
Idk if this is still happening but some links require permission to acess , any way that can be fixed?

**Comment by notsamicc** [comment]
i'll reupload them ig

**Comment by CoolNiteYT** [comment]
Wait. The first 5.00 just broke , but **it worked like yesterday!!?!?** 



what even is happening now this is just becoming so confusing

**Comment by notsamicc** [comment]
idk maybe they've been up for too long
