### ISSUE TITLE
URLs not working

### ISSUE THREAD

**Issue by zoaq1** [notsamicc/Fortnite-Builds#15]
the url needs to be http:// from what i've noticed, they are all https://

**Comment by notsamicc** [comment]
they're supposed to be https

**Comment by zoaq1** [comment]
![image](https://user-images.githubusercontent.com/93454464/152405639-f1980ba9-a2be-4670-b763-38a9d3ad8ccf.png)

**Comment by notsamicc** [comment]
what link is that

**Comment by zoaq1** [comment]
> what link is that

all of them

**Comment by notsamicc** [comment]
that's a problem on your end they're all finde for me

**Comment by notsamicc** [comment]
fine*
