### ISSUE TITLE
Links breaking (again)

### ISSUE THREAD

**Issue by CoolNiteYT** [notsamicc/Fortnite-Builds#16]
Just wanted to point out that some links seem to be breaking once again , i tried 7.00 and well it's broken... with the same permission error as last time (if i remember correctly)

Just wanted to point this out and see if you can fix this (like you fixed it last time)

Thanks

**Comment by Fischsalat** [comment]
I'll fix it if you give me a list of all broken builds.

**Comment by CoolNiteYT** [comment]
Afaik it's only 7.00 which broke

**Comment by Fischsalat** [comment]
fixed

**Comment by CoolNiteYT** [comment]
they've broken again , take a look at the issue which i just published
