### ISSUE TITLE
6.21 client crashes

### ISSUE THREAD

**Issue by da-droid** [notsamicc/Fortnite-Builds#2]
Fortnite client 6.21 crashes   OUT OF MEMORY

**Comment by da-droid** [comment]
LogMemory: Warning: Freeing 33554432 bytes from backup pool to handle out of memory.

LogMemory: Warning: MemoryStats:
        AvailablePhysical 11311333376
         AvailableVirtual 140728631775232
             UsedPhysical 2590687232
         PeakUsedPhysical 2634272768
              UsedVirtual 4099866624
          PeakUsedVirtual 4147679232

**Comment by notsamicc** [comment]
There's no known fix for this atm it just happens to some people

**Comment by da-droid** [comment]
Shit, I can't see the butterfly event because of this error, is there any way to visualize the old replays?

**Comment by notsamicc** [comment]
no
