### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by Alfonso27** [notsamicc/Fortnite-Builds#21]
Hi, I stumbled upon here looking for a way to play old versions of Fortnite and ask if it was possible to get old battle passes.  If so, how does it work?  Do I also have to download some files called "MANIFEST"?  Thanks to those who will answer

**Comment by notsamicc** [comment]
if you want to get old battle passes you'll have to use a backend that supports them. the builds labelled "MANIFEST" can be downloaded using a manifest downloader. vastblasts archive has a lot of manifests https://github.com/VastBlast/FortniteManifestArchive
