### ISSUE TITLE
4.2 access

### ISSUE THREAD

**Issue by FortniteGaemer** [notsamicc/Fortnite-Builds#22]
i tried downloading 4.2 but it is access restricted, it has been everytime ive tried to download it in the last week

**Comment by IsTheWit** [comment]
![image](https://user-images.githubusercontent.com/81376136/172494965-ee4ad9f6-9886-4d6d-a663-f804b80db5e3.png)

**Comment by IsTheWit** [comment]
says it on main page

**Comment by Fischsalat** [comment]
The build is still on GDrive and everything, it's just google being dumb and restricting access for no reason.
