### ISSUE TITLE
4.2

### ISSUE THREAD

**Issue by Tragic213** [notsamicc/Fortnite-Builds#23]
4.2 isn't working still. Kind of a bummer. I had to play the new event on my ipad.
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/107578503/173896804-dbd3c62f-392f-4a85-b02b-87cad1f11579.PNG">

**Comment by Milxnor** [comment]
Please read the readme next time.

**Comment by CoolNiteYT** [comment]
> Please read the readme next time. And the only other issue is about this too.

then again back when the readme was updated to say the 4.2 download didn't work it literally worked perfectly 💀
