### ISSUE TITLE
It's in google drive so it had a limit on the views and downloads

### ISSUE THREAD

**Issue by TheRaveninGitHub** [notsamicc/Fortnite-Builds#3]
Pls put it on something else instead of Google drive like mega or dropbox

**Comment by amazman** [comment]
yea i have this issue to please fix

**Comment by Fischsalat** [comment]
If one of you pays for MEGA or gives me like 40 microsoft accounts: sure

**Comment by notsamicc** [comment]
In the rift discord faq there is a tutorial to bypass this

**Comment by Fischsalat** [comment]
No, dont tell them. Now they dont send me money :(

**Comment by notsamicc** [comment]
💀
