### ISSUE TITLE
Error with version numbering.

### ISSUE THREAD

**Issue by Videogamer555** [notsamicc/Fortnite-Builds#6]
You show version 1.10-CL-3790078 as being the last version of Season 1, but when I play it text in the game says "season 2". So it appears that either this is the last version of season 1 but Epic Games accidentally mislabeled it, or version 1.10 is actually the first version of season 2 (not the last version of season 1), or else the link goes to the wrong version of the game (a version that's not actually version 1.10). How do I check what version it actually is? What file do I need to load into a hex editor or whatever, in order to verify the actual version number?

**Comment by notsamicc** [comment]
1.10 is the last build of season 1, it probably shows season 2 because of a mistake in the rift backend. You can check the version by right clicking the exe and clicking properties

**Comment by Fischsalat** [comment]
if you're funny you could open it in ida to be 100% sure
